[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
url = "2.2"

[[bin]]
name = "server"
path = "src/server.rs"